services:
  - type: web
    name: premium-reklam-api
    runtime: docker
    repo: https://github.com/BTB60/Premium-Reklam
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/ping
    autoDeploy: true


