-- İşçi tapşırıqları (admin panel)
CREATE TABLE IF NOT EXISTS worker_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    assigned_to_user_id BIGINT,
    status VARCHAR(30) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    due_date TIMESTAMP,
    work_started_at TIMESTAMP,
    order_id BIGINT,
    order_number VARCHAR(80),
    note TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT fk_worker_task_user FOREIGN KEY (assigned_to_user_id) REFERENCES users (id),
    CONSTRAINT fk_worker_task_order FOREIGN KEY (order_id) REFERENCES orders (id)
);
